services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"
    depends_on:
      - tomcat

  tomcat:
    build:
      context: .
      dockerfile: Dockerfile-tomcat
    ports:
      - "8080:8080" 
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - mariadb

  mariadb:
    build:
      context: .
      dockerfile: Dockerfile-mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306" 

