FROM httpd:latest

RUN sed -i '/^#LoadModule proxy_module/ s/^#//g' /usr/local/apache2/conf/httpd.conf
RUN sed -i '/^#LoadModule proxy_ajp_module/ s/^#//g' /usr/local/apache2/conf/httpd.conf
RUN sed -i '/^#LoadModule rewrite_module/ s/^#//g' /usr/local/apache2/conf/httpd.conf

COPY ./httpd.conf /usr/local/apache2/conf/httpd.conf

EXPOSE 80
